// Generated by scripts/gen-logo.mjs — run `npm run logo`, do not edit by hand.

/**
 * The Swarmterm mark for in-app chrome.
 *
 * This is the reduced form: the prompt alone, drawn heavy, with no extrusion.
 * The only surface that renders it is the title bar at 16px, and at that size
 * the extruded box collapses into a smudge — its strokes land below one pixel.
 * The chrome behind the glyph stands in for the box's front face.
 *
 * The full extruded mark ships as artwork instead, where it is seen large:
 * `src-tauri/icon-source.svg` and `docs/images/logo-*.png`.
 *
 * Strokes inherit `currentColor`, so it themes with whatever chrome hosts it.
 */
export function Logo({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 120 120"
      fill="none"
      stroke="currentColor"
      strokeWidth={12}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
      aria-hidden="true"
    >
      <path d="M24 84 L48 60 L24 36" />
      <path d="M60 84 L96 84" />
    </svg>
  )
}
